# Generated by Django 5.2 on 2025-07-24 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VwMercadoSuperFavoritoHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_event', models.BigIntegerField()),
                ('id_team_home', models.BigIntegerField()),
                ('name_home', models.CharField(db_collation='utf8mb4_0900_ai_ci', max_length=255)),
                ('icon_home', models.TextField(blank=True, db_collation='utf8mb4_0900_ai_ci', null=True)),
                ('id_team_away', models.BigIntegerField()),
                ('name_away', models.CharField(db_collation='utf8mb4_0900_ai_ci', max_length=255)),
                ('icon_away', models.TextField(blank=True, db_collation='utf8mb4_0900_ai_ci', null=True)),
                ('campeonato_name', models.CharField(db_collation='utf8mb4_0900_ai_ci', max_length=255)),
                ('mercado_name', models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', max_length=200, null=True)),
                ('odd', models.FloatField()),
                ('home_actual', models.BigIntegerField()),
                ('away_actual', models.BigIntegerField()),
                ('data_jogo', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vw_mercado_super_favorito_home',
                'managed': False,
            },
        ),
    ]
