# Generated by Django 5.2 on 2025-04-23 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_campeonato', models.CharField(max_length=200)),
                ('odd', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('resultado', models.CharField(choices=[('G', 'green'), ('R', 'red'), ('U', 'undefined')], max_length=1)),
                ('dia_semana', models.CharField(choices=[('DOMINGO', 'domingo'), ('SEGUNDA', 'segunda'), ('TERÇA', 'terça'), ('QUARTA', 'quarta'), ('QUINTA', 'quinta'), ('SEXTA', 'sexta'), ('SABADO', 'sábado')], max_length=20)),
                ('dia_evento', models.DateTimeField()),
                ('id_campeonato', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='analytics.tournament')),
                ('id_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.entrada')),
            ],
            options={
                'db_table': 'evento',
                'managed': True,
            },
        ),
    ]
