# Generated by Django 5.2 on 2025-04-16 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_tournament'),
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Eventos',
            new_name='Evento',
        ),
        migrations.AlterModelOptions(
            name='evento',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='evento',
            table='evento',
        ),
    ]
