# Generated by Django 5.2 on 2025-04-23 19:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Semana')),
                ('quantidade_apostas', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade Apostas')),
                ('total_entradas', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Total Investimentos')),
                ('total_retorno', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Total Investimentos')),
                ('data_inicial', models.DateField(verbose_name='Data Inicial')),
                ('data_final', models.DateField(verbose_name='Data Final')),
            ],
            options={
                'verbose_name': 'Resultado',
                'verbose_name_plural': 'LucResultadoros',
                'db_table': 'resultado',
                'ordering': ['-semana'],
            },
        ),
    ]
