# Generated by Django 5.2 on 2025-04-23 21:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciclo', '0006_delete_gerenciaciclo'),
        ('gerencia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GerenciaCiclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_total_entrada', models.IntegerField(blank=True, default=0, null=True)),
                ('valor_total_entrada', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Total de Entrada')),
                ('valor_total_retorno', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Total de Retorno')),
                ('ciclo', models.ForeignKey(blank=True, db_column='id_ciclo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gerencia_ciclo', to='ciclo.ciclo', verbose_name='gerencia')),
            ],
            options={
                'verbose_name': 'GerenciaCiclo',
                'verbose_name_plural': 'Gerencia Entrada',
                'db_table': 'gerencia_ciclo',
                'managed': True,
            },
        ),
    ]
