# Generated by Django 5.2 on 2025-04-23 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0002_gerenciaciclo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resultado',
        ),
    ]
