# Generated by Django 5.2 on 2025-06-02 18:00

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciclo', '0006_delete_gerenciaciclo'),
        ('gerencia', '0003_delete_resultado'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvolucaoSaldoAtual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor do Saldo Atual')),
                ('disponivel_entrada', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Disponivel Entrada')),
                ('data', models.DateField(default=datetime.date.today, verbose_name='Data da Alterção do sado inicial')),
                ('id_ciclo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evolucao_saldo_atual', to='ciclo.ciclo', verbose_name='ciclo')),
            ],
            options={
                'verbose_name': 'Evolução Saldo Atual',
                'verbose_name_plural': 'Evoluçao dos Saldos Atuais',
                'db_table': 'evolucao_saldo_atual',
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('id_ciclo', 'data'), name='unique_ciclo_data')],
            },
        ),
    ]
