# Generated by Django 5.2 on 2025-06-02 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciclo', '0006_delete_gerenciaciclo'),
        ('gerencia', '0004_evolucaosaldoatual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evolucaosaldoatual',
            name='id_ciclo',
            field=models.ForeignKey(blank=True, db_column='id_ciclo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evolucao_saldo_atual', to='ciclo.ciclo', verbose_name='ciclo'),
        ),
    ]
