# Generated by Django 5.2 on 2025-04-23 19:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('country_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ativo', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'tournament',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VwAnalyticsMercadoV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_event', models.BigIntegerField()),
                ('id_unique_tournament', models.BigIntegerField()),
                ('id_season', models.BigIntegerField()),
                ('id_home_team', models.BigIntegerField()),
                ('id_away_team', models.BigIntegerField()),
            ],
            options={
                'db_table': 'vw_analytics_mercado_v2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VwConsultaMercadoSf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_event', models.BigIntegerField()),
                ('mercado', models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', max_length=200, null=True)),
                ('odd', models.FloatField(blank=True, null=True)),
                ('home_actual', models.IntegerField(blank=True, null=True)),
                ('away_actual', models.IntegerField(blank=True, null=True)),
                ('data_jogo', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vw_consulta_mercado_sf',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id_event', models.IntegerField(primary_key=True, serialize=False)),
                ('mercado', models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', max_length=200, null=True)),
                ('odd', models.FloatField(default=0.0)),
                ('home_actual', models.IntegerField(default=0)),
                ('away_actual', models.IntegerField(blank=True, default=0, null=True)),
                ('data_jogo', models.DateTimeField(blank=True, null=True)),
                ('opcao_entrada', models.CharField(choices=[('A', 'aceitar'), ('R', 'recusar'), ('E', 'em_espera')], default='E', max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor de Entrada')),
                ('is_multipla', models.BooleanField(default=False, verbose_name='[0-simples, 1-multipla]')),
                ('cod_multipla', models.CharField(blank=True, max_length=20, null=True)),
                ('resultado_entrada', models.CharField(blank=True, choices=[('G', 'green'), ('R', 'red'), ('A', 'anulado')], max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'entrada',
                'verbose_name_plural': 'Entrada',
                'db_table': 'entrada',
                'ordering': ['-data_jogo'],
            },
        ),
    ]
