# Generated by Django 5.2 on 2025-04-23 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('ciclo', '0003_rename_id_ciclo_gerenciaciclo_ciclo'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='ciclo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entrada', to='ciclo.ciclo', verbose_name='entrada'),
        ),
    ]
