# Generated by Django 5.2 on 2025-04-12 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LittleFaith',
            fields=[
                ('id_event', models.IntegerField(primary_key=True, serialize=False)),
                ('mercado', models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', max_length=200, null=True)),
                ('odd', models.FloatField(blank=True, null=True)),
                ('home_actual', models.IntegerField(blank=True, null=True)),
                ('away_actual', models.IntegerField(blank=True, null=True)),
                ('data_jogo', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Little Faith',
                'verbose_name_plural': 'Little Faith',
                'ordering': ['-data_jogo'],
            },
        ),
    ]
