# Generated by Django 5.2 on 2025-04-13 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_littlefaith'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='littlefaith',
            options={'ordering': ['-data_jogo'], 'verbose_name': 'Little Faith', 'verbose_name_plural': 'Lucros'},
        ),
    ]
