# Generated by Django 5.2 on 2025-04-23 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_entrada_ciclo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrada',
            old_name='ciclo',
            new_name='id_ciclo',
        ),
    ]
