# Generated by Django 5.2 on 2025-04-23 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_rename_ciclo_entrada_id_ciclo'),
        ('ciclo', '0004_alter_gerenciaciclo_ciclo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrada',
            name='id_ciclo',
        ),
        migrations.AddField(
            model_name='entrada',
            name='ciclo',
            field=models.ForeignKey(blank=True, db_column='id_ciclo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entrada', to='ciclo.ciclo', verbose_name='ciclo'),
        ),
    ]
