# Generated by Django 5.2 on 2025-04-16 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_littlefaith_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='littlefaith',
            options={'ordering': ['-data_jogo'], 'verbose_name': 'Little Faith', 'verbose_name_plural': 'Little Faith'},
        ),
    ]
