# Generated by Django 5.2 on 2025-04-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_littlefaith_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='littlefaith',
            name='aposta_aceita',
            field=models.BooleanField(default=False),
        ),
    ]
