# Generated by Django 5.2 on 2025-04-16 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_alter_littlefaith_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='littlefaith',
            table='little_faith',
        ),
    ]
