# Generated by Django 5.2 on 2025-05-03 17:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_remove_entrada_id_ciclo_entrada_ciclo'),
        ('ciclo', '0006_delete_gerenciaciclo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrada',
            name='resultado_entrada',
        ),
        migrations.CreateModel(
            name='Aposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_entrada', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('odd', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('resultado', models.CharField(choices=[('G', 'green'), ('R', 'red'), ('A', 'anulado')], default='A', max_length=1)),
                ('data_resultado', models.DateTimeField(blank=True, null=True)),
                ('valor_retorno', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apostas', to='ciclo.ciclo')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apostas', to='analytics.entrada')),
            ],
            options={
                'verbose_name': 'Aposta',
                'verbose_name_plural': 'Apostas',
                'db_table': 'aposta',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
