# Generated by Django 5.2 on 2025-04-16 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_littlefaith_aposta_aceita'),
        ('analytics', '0005_alter_littlefaith_table'),
    ]

    operations = [
    ]
