# Generated by Django 5.2 on 2025-05-03 17:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_remove_entrada_resultado_entrada_aposta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='odd',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Odd'),
        ),
    ]
