# Generated by Django 5.2 on 2025-04-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_merge_20250416_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('country_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ativo', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'tournament',
                'managed': False,
            },
        ),
    ]
