# Generated by Django 5.2 on 2025-05-11 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_alter_entrada_odd'),
        ('ciclo', '0006_delete_gerenciaciclo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aposta',
            options={'ordering': ['-data_aposta'], 'verbose_name': 'Aposta', 'verbose_name_plural': 'Apostas'},
        ),
        migrations.RenameField(
            model_name='aposta',
            old_name='data_criacao',
            new_name='data_aposta',
        ),
        migrations.RenameField(
            model_name='aposta',
            old_name='evento',
            new_name='id_entrada',
        ),
        migrations.RenameField(
            model_name='aposta',
            old_name='valor_retorno',
            new_name='retorno',
        ),
        migrations.RenameField(
            model_name='aposta',
            old_name='valor_entrada',
            new_name='valor',
        ),
        migrations.RemoveField(
            model_name='aposta',
            name='ciclo',
        ),
        migrations.RemoveField(
            model_name='aposta',
            name='data_resultado',
        ),
        migrations.RemoveField(
            model_name='aposta',
            name='odd',
        ),
        migrations.RemoveField(
            model_name='entrada',
            name='ciclo',
        ),
        migrations.RemoveField(
            model_name='entrada',
            name='cod_multipla',
        ),
        migrations.RemoveField(
            model_name='entrada',
            name='is_multipla',
        ),
        migrations.RemoveField(
            model_name='entrada',
            name='valor',
        ),
        migrations.AddField(
            model_name='aposta',
            name='cod_multipla',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='aposta',
            name='id_ciclo',
            field=models.ForeignKey(blank=True, db_column='id_ciclo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aposta', to='ciclo.ciclo', verbose_name='ciclo'),
        ),
        migrations.AddField(
            model_name='aposta',
            name='is_multipla',
            field=models.BooleanField(default=False, verbose_name='[0-simples, 1-multipla]'),
        ),
    ]
