# Generated by Django 5.2 on 2025-05-11 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_alter_aposta_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aposta',
            old_name='id_ciclo',
            new_name='ciclo',
        ),
        migrations.RenameField(
            model_name='aposta',
            old_name='id_entrada',
            new_name='entrada',
        ),
    ]
