# Generated by Django 5.2 on 2025-04-17 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_tournament'),
        ('eventos', '0002_rename_eventos_evento_alter_evento_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LittleFaith',
            new_name='Entrada',
        ),
        migrations.AlterModelOptions(
            name='entrada',
            options={'ordering': ['-data_jogo'], 'verbose_name': 'entrada', 'verbose_name_plural': 'Entrada'},
        ),
        migrations.AlterModelTable(
            name='entrada',
            table='entrada',
        ),
    ]
