# Generated by Django 5.2 on 2025-04-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_rename_littlefaith_entrada_alter_entrada_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='away_actual',
            field=models.IntegerField(default=0),
        ),
    ]
