# Generated by Django 5.2 on 2025-05-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_rename_id_ciclo_aposta_ciclo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aposta',
            name='resultado',
            field=models.CharField(choices=[('G', 'green'), ('R', 'red'), ('A', 'anulado'), ('', 'selecione')], default='A', max_length=1),
        ),
    ]
