# Generated by Django 5.2 on 2025-05-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_alter_aposta_resultado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aposta',
            name='resultado',
            field=models.CharField(choices=[('G', 'green'), ('R', 'red'), ('A', 'anulado'), ('', 'selecione')], default='', max_length=1),
        ),
    ]
