# Generated by Django 5.2 on 2025-04-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0010_alter_entrada_away_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='away_actual',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='home_actual',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='odd',
            field=models.FloatField(default=0.0),
        ),
    ]
