# Generated by Django 5.2 on 2025-05-22 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0010_alter_aposta_resultado'),
    ]

    operations = [
        migrations.CreateModel(
            name='VwMercadoOwnerBallSfHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_campeonato', models.BigIntegerField()),
                ('entrada_mercado', models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', max_length=200, null=True)),
                ('odd', models.FloatField(blank=True, null=True)),
                ('data_jogo', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vw_mercado_owner_boll_sf_home',
                'managed': False,
            },
        ),
    ]
