# Generated by Django 5.2 on 2025-05-24 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0011_vwmercadoownerballsfhome'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vwmercadoownerballsfhome',
            table='vw_mercado_owner_boll_sf_home_v2',
        ),
    ]
