# Generated by Django 5.2 on 2025-04-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0011_alter_entrada_away_actual_alter_entrada_home_actual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='away_actual',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
