# Generated by Django 5.2 on 2025-04-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0012_alter_entrada_away_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='away_actual',
            field=models.IntegerField(default=0),
        ),
    ]
