# Generated by Django 5.2 on 2025-05-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0012_alter_vwmercadoownerballsfhome_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='odd_change',
            field=models.CharField(blank=True, choices=[('S', 'subiu'), ('D', 'desceu'), ('P', 'parada')], default='P', max_length=5),
        ),
    ]
