# Generated by Django 5.2 on 2025-04-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0013_alter_entrada_away_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='aposta_aceita',
            field=models.CharField(choices=[('A', 'aceitar'), ('R', 'recusar'), ('E', 'em_espera')], default='E', max_length=20),
        ),
    ]
