# Generated by Django 5.2 on 2025-05-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0013_entrada_odd_change'),
    ]

    operations = [
        migrations.CreateModel(
            name='OddChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_event', models.BigIntegerField()),
                ('home_fractional_value', models.FloatField(blank=True, null=True)),
                ('home_change_from_initial', models.FloatField(blank=True, null=True)),
                ('home_change_from_last', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'odd_change',
                'managed': False,
            },
        ),
    ]
