# Generated by Django 5.2 on 2025-04-19 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0015_rename_aposta_aceita_entrada_opcao_entrada'),
        ('periodo', '0002_alter_periodo_options_alter_periodo_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='id_periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='periodo.periodo', verbose_name='Período'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='is_multipla',
            field=models.BooleanField(default=False, verbose_name='[0-simples, 1-multipla]'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor de Entrada'),
        ),
    ]
