# Generated by Django 5.2 on 2025-06-09 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0015_vwmercadoownerballfavoritohome'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vwmercadoownerballsfhome',
            table='vw_mercado_owner_boll_super_favorito_home',
        ),
    ]
