# Generated by Django 5.2 on 2025-04-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0016_entrada_id_periodo_entrada_is_multipla_entrada_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='away_actual',
            field=models.IntegerField(),
        ),
    ]
