# Generated by Django 5.2 on 2025-06-15 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0017_vwmercadoownerballunder2_5'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aposta',
            options={'ordering': ['-id'], 'verbose_name': 'Aposta', 'verbose_name_plural': 'Apostas'},
        ),
    ]
