# Generated by Django 5.2 on 2025-06-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0018_alter_aposta_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='resultado_estatistica',
            field=models.BooleanField(default=0),
        ),
    ]
