# Generated by Django 5.2 on 2025-04-20 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0018_alter_entrada_away_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='cod_multipla',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
