# Generated by Django 5.2 on 2025-04-21 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0019_entrada_cod_multipla'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='resultado_entrada',
            field=models.CharField(blank=True, choices=[('G', 'green'), ('R', 'red'), ('A', 'anulado')], max_length=20, null=True),
        ),
    ]
