# Generated by Django 5.2 on 2025-07-24 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0019_entrada_resultado_estatistica'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='icon_home',
            field=models.TextField(blank=True, db_collation='utf8mb4_0900_ai_ci', null=True),
        ),
    ]
