# Generated by Django 5.2 on 2025-04-21 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0020_entrada_resultado_entrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Valor de Entrada'),
        ),
    ]
