# Generated by Django 5.2 on 2025-07-24 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0020_entrada_icon_home'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrada',
            old_name='icon_home',
            new_name='icon_home_data_url',
        ),
    ]
