# Generated by Django 5.2 on 2025-04-21 23:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0021_alter_entrada_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor de Entrada'),
        ),
    ]
