# Generated by Django 5.2 on 2025-07-24 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0021_rename_icon_home_entrada_icon_home_data_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='name_home',
            field=models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', max_length=255, null=True),
        ),
    ]
