# Generated by Django 5.2 on 2025-04-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0022_alter_entrada_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='away_actual',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
