# Generated by Django 5.2 on 2025-07-24 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0022_entrada_name_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='icon_away_data_url',
            field=models.TextField(blank=True, db_collation='utf8mb4_0900_ai_ci', null=True),
        ),
        migrations.AddField(
            model_name='entrada',
            name='name_away',
            field=models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', max_length=255, null=True),
        ),
    ]
