# Generated by Django 5.2 on 2025-07-26 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0023_entrada_icon_away_data_url_entrada_name_away'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='resultado_entrada',
            field=models.CharField(choices=[('G', 'green'), ('R', 'red')], max_length=20, null=True),
        ),
    ]
