# Generated by Django 5.2 on 2025-04-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0023_alter_entrada_away_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='away_actual',
            field=models.TextField(default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='home_actual',
            field=models.TextField(default='0', max_length=10, null=True),
        ),
    ]
