# Generated by Django 5.2 on 2025-07-27 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0024_entrada_resultado_entrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='resultado_entrada',
            field=models.CharField(choices=[('G', 'ganhou'), ('E', 'empatou'), ('P', 'perdeu')], max_length=20, null=True),
        ),
    ]
