# Generated by Django 5.2 on 2025-04-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0025_alter_entrada_away_actual_alter_entrada_home_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='away_actual',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='home_actual',
            field=models.IntegerField(default=0),
        ),
    ]
