# Generated by Django 5.2 on 2025-07-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0025_alter_entrada_resultado_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='next_event_priority',
            field=models.BooleanField(default=0),
        ),
    ]
