# Generated by Django 5.2 on 2025-08-15 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0026_entrada_next_event_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='event_vote_home',
            field=models.BooleanField(default=0),
        ),
    ]
