# Generated by Django 5.2 on 2025-04-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0026_alter_entrada_away_actual_alter_entrada_home_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='away_actual',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
