# Generated by Django 5.2 on 2025-04-23 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0027_alter_entrada_away_actual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrada',
            name='id_periodo',
        ),
    ]
