# Generated by Django 5.2 on 2025-08-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0027_entrada_event_vote_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='event_vote_home',
            field=models.CharField(choices=[('H', 'home'), ('A', 'away'), ('N', 'none')], default='N', max_length=20),
        ),
    ]
