# Generated by Django 5.2 on 2025-08-21 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0028_alter_entrada_event_vote_home'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VwMercadoOwnerBallFavoritoHome',
        ),
        migrations.DeleteModel(
            name='VwMercadoOwnerBallSfHome',
        ),
        migrations.DeleteModel(
            name='VwMercadoOwnerBallUnder2_5',
        ),
    ]
