# Generated by Django 5.2 on 2025-04-23 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0028_remove_entrada_id_periodo'),
        ('ciclo', '0003_cicloentrada_delete_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='id_ciclo_entrada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='ciclo.cicloentrada', verbose_name='Ciclo'),
        ),
    ]
