# Generated by Django 5.2 on 2025-08-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0029_delete_vwmercadoownerballfavoritohome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='opcao_entrada',
            field=models.CharField(choices=[('A', 'aceitar'), ('R', 'recusar'), ('E', 'em_espera')], default='W', max_length=20),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='resultado_entrada',
            field=models.CharField(choices=[('W', 'win'), ('D', 'drow'), ('L', 'lose')], max_length=20, null=True),
        ),
    ]
