# Generated by Django 5.2 on 2025-10-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0032_alter_entrada_entry_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='away_vote',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='entrada',
            name='home_vote',
            field=models.IntegerField(default=0),
        ),
    ]
