# Generated by Django 5.2 on 2025-10-28 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0033_entrada_away_vote_entrada_home_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='aposta',
            name='color_multipla',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
