# Generated by Django 5.2 on 2025-11-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0034_aposta_color_multipla'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='away_probability',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entrada',
            name='home_probability',
            field=models.IntegerField(default=0),
        ),
    ]
