# Generated by Django 5.2 on 2025-11-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0035_entrada_away_probability_entrada_home_probability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrada',
            old_name='away_probability',
            new_name='away_win',
        ),
        migrations.RenameField(
            model_name='entrada',
            old_name='home_probability',
            new_name='home_win',
        ),
        migrations.AddField(
            model_name='entrada',
            name='draw_probability',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
