# Generated by Django 5.2 on 2025-11-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0036_rename_away_probability_entrada_away_win_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='id_away',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='entrada',
            name='id_home',
            field=models.BigIntegerField(null=True),
        ),
    ]
