# Generated by Django 5.2 on 2026-02-02 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0037_entrada_id_away_entrada_id_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
