# Generated by Django 5.2 on 2026-02-26 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0038_entrada_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='tournament',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
