# Generated by Django 5.2 on 2026-02-26 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0039_entrada_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='ia_away',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='entrada',
            name='ia_draw',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='entrada',
            name='ia_home',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
