# Generated by Django 5.2 on 2026-02-26 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0040_entrada_ia_away_entrada_ia_draw_entrada_ia_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='ia_away',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='ia_draw',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='ia_home',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
