# Generated by Django 5.2 on 2025-07-21 10:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaOwnerBall',
            fields=[
                ('id_event', models.IntegerField(primary_key=True, serialize=False)),
                ('mercado', models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', max_length=200, null=True)),
                ('odd_change', models.CharField(blank=True, choices=[('S', 'subiu'), ('D', 'desceu'), ('P', 'parada')], default='P', max_length=5)),
                ('odd', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Odd')),
                ('home_actual', models.IntegerField(default=0)),
                ('away_actual', models.IntegerField(blank=True, default=0, null=True)),
                ('data_jogo', models.DateTimeField(blank=True, null=True)),
                ('opcao_entrada', models.CharField(choices=[('A', 'aceitar'), ('R', 'recusar'), ('E', 'em_espera')], default='E', max_length=20)),
                ('resultado_estatistica', models.BooleanField(default=0)),
            ],
            options={
                'verbose_name': 'entrada_owner_ball',
                'verbose_name_plural': 'entrada_owner_ball',
                'db_table': 'entrada_owner_ball',
                'ordering': ['-data_jogo'],
            },
        ),
    ]
