# Generated by Django 5.2 on 2025-08-21 20:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_ball', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VwMercadoOwnerBallFavoritoHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada_mercado', models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', max_length=200, null=True)),
                ('odd', models.FloatField(blank=True, null=True)),
                ('data_jogo', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vw_mercado_owner_ball_favorito_home',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VwMercadoOwnerBallSfHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_event', models.BigIntegerField()),
                ('mercado', models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', max_length=200, null=True)),
                ('odd', models.FloatField(blank=True, null=True)),
                ('home_actual', models.IntegerField(blank=True, null=True)),
                ('away_actual', models.IntegerField(blank=True, null=True)),
                ('data_jogo', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vw_mercado_owner_boll_super_favorito_home',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VwMercadoOwnerBallUnder2_5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada_mercado', models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', max_length=200, null=True)),
                ('odd', models.FloatField(blank=True, null=True)),
                ('data_jogo', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vw_mercado_owner_ball_under_2_5',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IncomingOwnerBallFavoriteHome',
            fields=[
                ('id_event', models.IntegerField(primary_key=True, serialize=False)),
                ('mercado', models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', max_length=200, null=True)),
                ('odd_change', models.CharField(blank=True, choices=[('S', 'subiu'), ('D', 'desceu'), ('P', 'parada')], default='P', max_length=5)),
                ('odd', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Odd')),
                ('home_actual', models.IntegerField(default=0)),
                ('away_actual', models.IntegerField(blank=True, default=0, null=True)),
                ('data_jogo', models.DateTimeField(blank=True, null=True)),
                ('opcao_entrada', models.CharField(choices=[('A', 'aceitar'), ('R', 'recusar'), ('E', 'em_espera')], default='E', max_length=20)),
                ('resultado_estatistica', models.BooleanField(default=0)),
            ],
            options={
                'verbose_name': 'icomming_owner_ball_favorite_home',
                'verbose_name_plural': 'icomming_owner_ball_favorite_home',
                'db_table': 'icomming_owner_ball_favorite_home',
                'ordering': ['-data_jogo'],
            },
        ),
    ]
