# Generated by Django 5.2 on 2025-08-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_ball', '0002_vwmercadoownerballfavoritohome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingownerballfavoritehome',
            name='resultado_entrada',
            field=models.CharField(choices=[('G', 'ganhou'), ('E', 'empatou'), ('P', 'perdeu')], max_length=20, null=True),
        ),
    ]
