# Generated by Django 5.2 on 2025-08-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_ball', '0003_incomingownerballfavoritehome_resultado_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradaownerball',
            name='resultado_entrada',
            field=models.CharField(choices=[('G', 'ganhou'), ('E', 'empatou'), ('P', 'perdeu')], max_length=20, null=True),
        ),
    ]
