# Generated by Django 5.2 on 2025-08-23 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner_ball', '0004_entradaownerball_resultado_entrada'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EntradaOwnerBall',
            new_name='SuperFavoriteHomeBallOwnerEntry',
        ),
    ]
