# Generated by Django 5.2 on 2025-08-23 11:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_ball', '0005_rename_entradaownerball_superfavoriteballownerentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteHomeBallOwnerEntry',
            fields=[
                ('id_event', models.IntegerField(primary_key=True, serialize=False)),
                ('market', models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', max_length=200, null=True)),
                ('odd_change', models.CharField(blank=True, choices=[('U', 'up'), ('D', 'dow'), ('S', 'stop')], default='S', max_length=5)),
                ('odd', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Odd')),
                ('home_actual', models.IntegerField(default=0)),
                ('away_actual', models.IntegerField(blank=True, default=0, null=True)),
                ('event_date', models.DateTimeField(blank=True, null=True)),
                ('entry_option', models.CharField(choices=[('A', 'accept'), ('R', 'refuse'), ('W', 'wait')], default='W', max_length=20)),
                ('statistic_result', models.BooleanField(default=0)),
                ('entry_result', models.CharField(choices=[('W', 'win'), ('D', 'drow'), ('L', 'lose')], max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'favorite_home_ball_owner_entry',
                'verbose_name_plural': 'favorite_home_ball_owner_entry',
                'db_table': 'favorite_home_ball_owner_entry',
                'ordering': ['-event_date'],
            },
        ),
        migrations.DeleteModel(
            name='IncomingOwnerBallFavoriteHome',
        ),
        migrations.AlterModelOptions(
            name='superfavoritehomeballownerentry',
            options={'ordering': ['-event_date'], 'verbose_name': 'super_favorite_home_ball_owner_entry', 'verbose_name_plural': 'super_favorite_home_ball_owner_entry'},
        ),
        migrations.RenameField(
            model_name='superfavoritehomeballownerentry',
            old_name='data_jogo',
            new_name='event_date',
        ),
        migrations.RenameField(
            model_name='superfavoritehomeballownerentry',
            old_name='mercado',
            new_name='market',
        ),
        migrations.RenameField(
            model_name='superfavoritehomeballownerentry',
            old_name='resultado_estatistica',
            new_name='statistic_result',
        ),
        migrations.RemoveField(
            model_name='superfavoritehomeballownerentry',
            name='opcao_entrada',
        ),
        migrations.RemoveField(
            model_name='superfavoritehomeballownerentry',
            name='resultado_entrada',
        ),
        migrations.AddField(
            model_name='superfavoritehomeballownerentry',
            name='entry_option',
            field=models.CharField(choices=[('A', 'accept'), ('R', 'refuse'), ('W', 'wait')], default='W', max_length=20),
        ),
        migrations.AddField(
            model_name='superfavoritehomeballownerentry',
            name='entry_result',
            field=models.CharField(choices=[('W', 'win'), ('D', 'drow'), ('L', 'lose')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='superfavoritehomeballownerentry',
            name='odd_change',
            field=models.CharField(blank=True, choices=[('U', 'up'), ('D', 'dow'), ('S', 'stop')], default='P', max_length=5),
        ),
        migrations.AlterModelTable(
            name='superfavoritehomeballownerentry',
            table='super_favorite_home_ball_owner_entry',
        ),
    ]
