# Generated by Django 5.2 on 2025-09-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_ball', '0006_favoritehomeballownerentry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleOwnerBall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('W', 'Weekly'), ('B', 'Biweekly'), ('M', 'Monthly')], default='W', max_length=20)),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('available_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
            ],
            options={
                'verbose_name': 'Cycle Owner Ball',
                'verbose_name_plural': 'Cycle Owner Ball',
                'db_table': 'cycle_owner_ball',
                'ordering': ['-start_date'],
                'managed': True,
            },
        ),
    ]
