# Generated by Django 5.2 on 2025-09-07 11:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_ball', '0007_cycleownerball'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetOwnerBall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_multiple', models.BooleanField(default=False, verbose_name='[0-simple, 1-multiple]')),
                ('cod_multiple', models.CharField(blank=True, max_length=20, null=True)),
                ('result', models.CharField(choices=[('G', 'Green'), ('R', 'Red'), ('C', 'Canceled'), ('', 'selecione')], default='', max_length=1)),
                ('value_bet', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('return_bet', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_bet', models.DateTimeField(auto_now_add=True)),
                ('cycle_owner_ball', models.ForeignKey(blank=True, db_column='id_cycle', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bet_owner_ball', to='owner_ball.cycleownerball', verbose_name='cycle')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets_owner_ball', to='owner_ball.superfavoritehomeballownerentry')),
            ],
            options={
                'verbose_name': 'BetOwnerBall',
                'verbose_name_plural': 'BetsOwnerBall',
                'db_table': 'bet_owner_ball',
                'ordering': ['-id'],
            },
        ),
    ]
