# Generated by Django 5.2 on 2025-09-07 22:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciclo', '0006_delete_gerenciaciclo'),
        ('owner_ball', '0008_betownerball'),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleManagerOwnerBall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_entries_number', models.IntegerField(blank=True, default=0, null=True)),
                ('total_entries_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Total de Entrada')),
                ('total_return_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Total de Retorno')),
                ('cycle', models.ForeignKey(blank=True, db_column='id_ciclo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cycle_manager_owner_ball', to='ciclo.ciclo', verbose_name='cycle_manager_owner_ball')),
            ],
            options={
                'verbose_name': 'CycleManagerOwnerBall',
                'verbose_name_plural': 'Cycle Manager Owner Ball',
                'db_table': 'cycle_manager_owner_ball',
                'managed': True,
            },
        ),
    ]
