# Generated by Django 5.2 on 2025-09-10 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_ball', '0009_cyclemanagerownerball'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cyclemanagerownerball',
            name='cycle',
            field=models.ForeignKey(blank=True, db_column='id_ciclo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cycle_manager_owner_ball', to='owner_ball.cycleownerball', verbose_name='cycle_manager_owner_ball'),
        ),
    ]
