# Generated by Django 5.2 on 2025-09-14 11:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_ball', '0010_alter_cyclemanagerownerball_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycleownerball',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cycleownerball',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cyclemanagerownerball',
            name='cycle',
            field=models.ForeignKey(db_column='id_ciclo', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cycle_manager_owner_ball', to='owner_ball.cycleownerball', verbose_name='cycle_manager_owner_ball'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cycleownerball',
            name='available_value',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='cycleownerball',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddConstraint(
            model_name='cycleownerball',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='end_date_after_start_date'),
        ),
        migrations.AddConstraint(
            model_name='cycleownerball',
            constraint=models.CheckConstraint(condition=models.Q(('available_value__lte', models.F('current_balance'))), name='available_value_not_greater_than_balance'),
        ),
    ]
