# Generated by Django 5.2 on 2025-10-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_ball', '0011_cycleownerball_created_at_cycleownerball_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='superfavoritehomeballownerentry',
            name='event_vote_home',
            field=models.CharField(choices=[('H', 'home'), ('A', 'away'), ('N', 'none')], default='N', max_length=20),
        ),
    ]
