# Generated by Django 5.2 on 2025-10-17 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_ball', '0012_superfavoritehomeballownerentry_event_vote_home'),
    ]

    operations = [
        migrations.RenameField(
            model_name='superfavoritehomeballownerentry',
            old_name='market',
            new_name='placar',
        ),
        migrations.AddField(
            model_name='superfavoritehomeballownerentry',
            name='icon_away',
            field=models.TextField(blank=True, db_collation='utf8mb4_0900_ai_ci', null=True),
        ),
        migrations.AddField(
            model_name='superfavoritehomeballownerentry',
            name='icon_home',
            field=models.TextField(blank=True, db_collation='utf8mb4_0900_ai_ci', null=True),
        ),
        migrations.AddField(
            model_name='superfavoritehomeballownerentry',
            name='name_away',
            field=models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='superfavoritehomeballownerentry',
            name='name_home',
            field=models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', max_length=255, null=True),
        ),
    ]
