# Generated by Django 5.2 on 2025-10-27 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_ball', '0013_rename_market_superfavoritehomeballownerentry_placar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='superfavoritehomeballownerentry',
            name='id_away',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='superfavoritehomeballownerentry',
            name='id_home',
            field=models.IntegerField(null=True),
        ),
    ]
