# Generated by Django 5.2 on 2025-11-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_ball', '0015_alter_superfavoritehomeballownerentry_entry_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='superfavoritehomeballownerentry',
            name='away_win',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='superfavoritehomeballownerentry',
            name='draw_probability',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='superfavoritehomeballownerentry',
            name='home_win',
            field=models.IntegerField(default=0),
        ),
    ]
