# Generated by Django 5.2 on 2025-11-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_ball', '0016_superfavoritehomeballownerentry_away_win_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='betownerball',
            name='color_multiple',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
