# Generated by Django 5.2 on 2025-07-22 20:05

import team.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id_team', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('ativo', models.SmallIntegerField()),
                ('icon', models.TextField(blank=True, help_text='Icone em formato base64', null=True)),
            ],
            options={
                'db_table': 'team_sofascore',
                'managed': False,
            },
        ),
    ]
