# Generated by Django 5.2 on 2025-07-22 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team',
            new_name='TeamSofascore',
        ),
    ]
