# Generated by Django 5.2 on 2025-04-12 16:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lucro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Semana')),
                ('quantidade_apostas', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade Apostas')),
                ('valor_inidividual_aposta', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Individual Aposta')),
                ('data_inicial', models.DateField(verbose_name='Data Inicial')),
                ('data_final', models.DateField(verbose_name='Data Final')),
            ],
            options={
                'verbose_name': 'Lucro',
                'verbose_name_plural': 'Lucros',
                'ordering': ['-semana'],
            },
        ),
    ]
