# Generated by Django 5.2 on 2025-04-16 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lucro', '0003_rename_lucrosemana_lucro'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='lucro',
            table='lucro',
        ),
    ]
