# Generated by Django 5.2 on 2025-04-16 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lucro', '0004_alter_lucro_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lucro',
            new_name='Resultado',
        ),
        migrations.AlterModelOptions(
            name='resultado',
            options={'ordering': ['-semana'], 'verbose_name': 'Resultado', 'verbose_name_plural': 'LucResultadoros'},
        ),
        migrations.AlterModelTable(
            name='resultado',
            table='resultado',
        ),
    ]
