# Generated by Django 5.2 on 2025-04-21 22:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lucro', '0005_rename_lucro_resultado_alter_resultado_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultado',
            name='valor_inidividual_aposta',
        ),
        migrations.AddField(
            model_name='resultado',
            name='total_entradas',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Total Investimentos'),
        ),
        migrations.AddField(
            model_name='resultado',
            name='total_retorno',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Total Investimentos'),
        ),
    ]
