# Generated by Django 5.2 on 2025-04-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periodo',
            options={'managed': True, 'ordering': ['-data_inicial'], 'verbose_name': 'Período', 'verbose_name_plural': 'Períodos'},
        ),
        migrations.AlterField(
            model_name='periodo',
            name='categoria',
            field=models.CharField(choices=[('S', 'Semanal'), ('Q', 'Quinzenal'), ('M', 'Mensal')], default='S', max_length=20),
        ),
    ]
