# Generated by Django 5.2 on 2026-01-20 22:22

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('logo', models.URLField(blank=True, max_length=500, null=True)),
                ('country_name', models.CharField(max_length=100)),
                ('coyntry_code', django_countries.fields.CountryField(max_length=2)),
                ('country_flag', models.URLField(blank=True, max_length=500, null=True)),
                ('season_year', models.PositiveIntegerField(default=2026)),
                ('season_start', models.DateField()),
                ('season_end', models.DateField()),
                ('season_coverege_perdictions', models.BooleanField(default=False, help_text='Possui Predictions')),
            ],
            options={
                'db_table': 'league',
                'managed': True,
            },
        ),
    ]
