# Generated by Django 5.2 on 2026-01-22 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
