# Generated by Django 5.2 on 2026-01-22 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_rename_season_coverege_perdictions_league_season_coverege_predictions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='league',
            old_name='coyntry_code',
            new_name='country_code',
        ),
    ]
