# Generated by Django 5.2 on 2026-01-22 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_rename_coyntry_code_league_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='country_code',
            field=models.CharField(max_length=10),
        ),
    ]
