# Generated by Django 5.2 on 2026-01-22 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_alter_league_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='season_end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='season_start',
            field=models.DateField(null=True),
        ),
    ]
