# Generated by Django 5.2 on 2026-01-27 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0002_rename_team_teamsofascore'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamSports',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=255)),
                ('logo', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'team_sports',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TeamSofascoreVsTeamSports',
            fields=[
                ('sofascore_team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='sofascore_mappings', serialize=False, to='team.teamsofascore')),
                ('date_mapping', models.DateTimeField(auto_now_add=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('sports_team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sports_mappings', to='team_sports.teamsports')),
            ],
            options={
                'verbose_name': 'Mapeamento Sofascore-Sports',
                'verbose_name_plural': 'Mapeamentos Sofascore-Sports',
                'db_table': 'team_sofascore_vs_team_sports',
                'managed': True,
                'indexes': [models.Index(fields=['sofascore_team', 'sports_team'], name='team_sofasc_sofasco_15f3bd_idx')],
                'unique_together': {('sofascore_team', 'sports_team')},
            },
        ),
    ]
