# Generated by Django 5.2 on 2025-04-23 20:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('S', 'Semanal'), ('Q', 'Quinzenal'), ('M', 'Mensal')], default='S', max_length=20)),
                ('saldo_atual', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor_disponivel_entrada', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data_inicial', models.DateField(verbose_name='Data Inicial')),
                ('data_final', models.DateField(verbose_name='Data Final')),
            ],
            options={
                'verbose_name': 'CicloEntrada',
                'verbose_name_plural': 'Ciclo Entrada',
                'db_table': 'ciclo_entrada',
                'ordering': ['-data_inicial'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GerenciaCiclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_total_entrada', models.IntegerField(blank=True, default=0, null=True)),
                ('valor_total_entrada', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Total de Entrada')),
                ('valor_total_retorno', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Total de Retorno')),
                ('id_ciclo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gerencia_ciclo', to='ciclo.ciclo', verbose_name='Gerencia Ciclo')),
            ],
        ),
    ]
