# Generated by Django 5.2 on 2025-04-23 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ciclo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciclo',
            options={'managed': True, 'ordering': ['-data_inicial'], 'verbose_name': 'Ciclo', 'verbose_name_plural': 'Ciclo'},
        ),
        migrations.AlterModelOptions(
            name='gerenciaciclo',
            options={'managed': True, 'verbose_name': 'GerenciaCiclo', 'verbose_name_plural': 'Gerencia Entrada'},
        ),
        migrations.AlterModelTable(
            name='ciclo',
            table='ciclo',
        ),
        migrations.AlterModelTable(
            name='gerenciaciclo',
            table='gerencia_ciclo',
        ),
    ]
