# Generated by Django 5.2 on 2025-04-23 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ciclo', '0002_alter_ciclo_options_alter_gerenciaciclo_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gerenciaciclo',
            old_name='id_ciclo',
            new_name='ciclo',
        ),
    ]
