# Generated by Django 5.2 on 2025-04-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0028_remove_entrada_id_periodo'),
        ('ciclo', '0002_alter_periodo_options_alter_periodo_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='CicloEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('S', 'Semanal'), ('Q', 'Quinzenal'), ('M', 'Mensal')], default='S', max_length=20)),
                ('saldo_atual', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor_disponivel_entrada', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data_inicial', models.DateField(verbose_name='Data Inicial')),
                ('data_final', models.DateField(verbose_name='Data Final')),
            ],
            options={
                'verbose_name': 'Ciclo',
                'verbose_name_plural': 'Ciclo',
                'db_table': 'ciclo',
                'ordering': ['-data_inicial'],
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='Periodo',
        ),
    ]
