# Generated by Django 5.2 on 2025-04-23 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ciclo', '0003_cicloentrada_delete_periodo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cicloentrada',
            options={'managed': True, 'ordering': ['-data_inicial'], 'verbose_name': 'CicloEntrada', 'verbose_name_plural': 'Ciclo Entrada'},
        ),
        migrations.AlterModelTable(
            name='cicloentrada',
            table='ciclo_entrada',
        ),
    ]
