# Generated by Django 5.2 on 2025-04-23 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciclo', '0003_rename_id_ciclo_gerenciaciclo_ciclo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gerenciaciclo',
            name='ciclo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gerencia_ciclo', to='ciclo.ciclo', verbose_name='gerencia'),
        ),
    ]
