# Generated by Django 5.2 on 2025-04-23 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ciclo', '0005_alter_gerenciaciclo_ciclo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GerenciaCiclo',
        ),
    ]
