# Generated by Django 5.2 on 2025-08-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueTournament',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('icon', models.TextField(blank=True, db_comment='Logo do Evento em base64 (estimativa: <65KB)', null=True)),
            ],
            options={
                'db_table': 'unique_tournament',
                'managed': False,
            },
        ),
    ]
