# Generated by Django 5.2 on 2025-08-11 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unique_tournament', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uniquetournament',
            options={'managed': True},
        ),
    ]
