# Generated by Django 5.2 on 2025-08-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unique_tournament', '0002_alter_uniquetournament_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniquetournament',
            name='icon',
            field=models.TextField(blank=True, db_comment='Logo do time em base64 (estimativa: <65KB)', null=True),
        ),
    ]
