# Generated by Django 5.2 on 2025-08-11 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unique_tournament', '0003_alter_uniquetournament_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uniquetournament',
            options={'managed': False},
        ),
    ]
