# Generated by Django 5.2 on 2026-01-08 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unique_tournament', '0004_alter_uniquetournament_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uniquetournament',
            options={'managed': True},
        ),
    ]
