# Generated by Django 5.2 on 2026-01-08 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unique_tournament', '0005_alter_uniquetournament_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniquetournament',
            name='country_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uniquetournament',
            name='end_date_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uniquetournament',
            name='has_groups',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='uniquetournament',
            name='has_rounds',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='uniquetournament',
            name='id_team_most_titles',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='uniquetournament',
            name='id_team_title_holder',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='uniquetournament',
            name='start_date_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
