# Generated by Django 5.2 on 2026-01-16 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unique_tournament', '0006_uniquetournament_country_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uniquetournament',
            name='id_team_most_titles',
        ),
        migrations.AddField(
            model_name='uniquetournament',
            name='ids_teams_most_titles',
            field=models.TextField(blank=True, db_comment='Armazena os IDS dos times com mais titulos', null=True),
        ),
    ]
