# Generated by Django 5.2 on 2026-01-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unique_tournament', '0007_remove_uniquetournament_id_team_most_titles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniquetournament',
            name='ids_teams_most_titles',
            field=models.CharField(blank=True, db_comment='Armazena os IDS dos times com mais titulos', max_length=255, null=True),
        ),
    ]
